- id: '1583530252657'
  alias: Tänd muminskåp på helgen
  description: ''
  trigger:
  - event: sunset
    offset: +00:45:00
    platform: sun
  condition:
  - condition: state
    entity_id: group.people
    state: home
  - condition: time
    weekday:
    - fri
    - sat
    - sun
  action:
  - device_id: f021ae88c9c94bb9b00a399eaab1019d
    domain: switch
    entity_id: switch.innr_sp_120_59328903_on_off
    type: turn_on
- id: '1583530546061'
  alias: Släck muminskåp på helgen
  description: ''
  trigger:
  - at: '23:00:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - fri
    - sat
    - sun
  action:
  - device_id: f021ae88c9c94bb9b00a399eaab1019d
    domain: switch
    entity_id: switch.innr_sp_120_59328903_on_off
    type: turn_off
- id: '1583772997902'
  alias: Tänd blå boll
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - device_id: 8269351cd5fd4ab7aa20a373c72279d3
    domain: switch
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_5ddf51fe_on_off
    type: turn_on
- id: '1583773386688'
  alias: Släck blå boll (vardag)
  description: ''
  trigger:
  - at: '22:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - device_id: 8269351cd5fd4ab7aa20a373c72279d3
    domain: switch
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_5ddf51fe_on_off
    type: turn_off
- id: '1583773386689'
  alias: Släck blå boll (helg)
  description: ''
  trigger:
  - at: '23:59:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - device_id: 8269351cd5fd4ab7aa20a373c72279d3
    domain: switch
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_5ddf51fe_on_off
    type: turn_off
