- id: '1583530252657'
  alias: Legoskåp tänd
  description: ''
  trigger:
  - event: sunset
    offset: +00:45:00
    platform: sun
  condition:
  - condition: state
    entity_id: group.people
    state: home
  - condition: time
    weekday:
    - fri
    - sat
    - sun
  action:
  - device_id: f021ae88c9c94bb9b00a399eaab1019d
    domain: switch
    entity_id: switch.innr_sp_120_59328903_on_off
    type: turn_on
  mode: single
- id: '1583530546061'
  alias: Legoskåp släck
  description: ''
  trigger:
  - at: '23:00:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - fri
    - sat
    - sun
  action:
  - device_id: f021ae88c9c94bb9b00a399eaab1019d
    domain: switch
    entity_id: switch.innr_sp_120_59328903_on_off
    type: turn_off
  mode: single
- id: 1583772997902_boll_on
  alias: Blå boll tänd
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - device_id: 8269351cd5fd4ab7aa20a373c72279d3
    domain: switch
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_5ddf51fe_on_off
    type: turn_on
- id: 1583773386688_boll_off_vardag
  alias: Blå boll släck (vardag)
  description: ''
  trigger:
  - at: '22:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - device_id: 8269351cd5fd4ab7aa20a373c72279d3
    domain: switch
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_5ddf51fe_on_off
    type: turn_off
- id: 1583773386689_boll_off_helg
  alias: Blå boll släck (helg)
  description: ''
  trigger:
  - at: '23:59:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - device_id: 8269351cd5fd4ab7aa20a373c72279d3
    domain: switch
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_5ddf51fe_on_off
    type: turn_off
- id: '1583773805811'
  alias: TV-skåp tänd
  description: ''
  trigger:
  - platform: time
    at: '18:00:00'
  - platform: sun
    event: sunset
  condition:
  - condition: sun
    after: sunset
  - condition: time
    after: '18:00:00'
  action:
  - device_id: 67515fccbe29472c8032217b84fb9b1b
    domain: switch
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_3d4ac3fe_on_off
    type: turn_on
- id: '1583773866555'
  alias: TV-skåp släck
  description: ''
  trigger:
  - at: '22:00:00'
    platform: time
  condition: []
  action:
  - device_id: 67515fccbe29472c8032217b84fb9b1b
    domain: switch
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_3d4ac3fe_on_off
    type: turn_off
- id: '1584047833146'
  alias: Korgar tänd
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.philips_lta001_5a422d08_level_light_color_on_off
      color_temp: 430
      brightness: 160
  - service: light.turn_on
    data:
      entity_id: light.philips_lta001_40e83008_level_light_color_on_off
      color_temp: 430
      brightness: 160
  - service: light.turn_on
    data:
      entity_id: light.philips_lta001_bc2fab08_level_light_color_on_off
      color_temp: 430
      brightness: 160
- id: '1584047917317'
  alias: Korgar släck
  description: ''
  trigger:
  - at: '23:00:00'
    platform: time
  condition: []
  action:
  - device_id: 061954fe386a4b719682f1c47e0ccc51
    domain: light
    entity_id: light.philips_lta001_5a422d08_level_light_color_on_off
    type: turn_off
  - device_id: 82728923eede491cb884a7f734b6c735
    domain: light
    entity_id: light.philips_lta001_40e83008_level_light_color_on_off
    type: turn_off
  - device_id: e804df0452714102837f74a408071aa7
    domain: light
    entity_id: light.philips_lta001_bc2fab08_level_light_color_on_off
    type: turn_off
- id: '1620915831174'
  alias: Hallautomation
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: 0636d3c8b83e02ef17b6b7f4350af0c2
    entity_id: binary_sensor.hallsensor_occupancy
    domain: binary_sensor
  condition:
  - type: is_illuminance
    condition: device
    device_id: 0636d3c8b83e02ef17b6b7f4350af0c2
    entity_id: sensor.hallsensor_illuminance
    domain: sensor
    below: 20
  action:
  - type: turn_on
    device_id: a9b757038722af90948fd69813460753
    entity_id: light.hallampa
    domain: light
    brightness_pct: 100
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: a9b757038722af90948fd69813460753
    entity_id: light.hallampa
    domain: light
  mode: restart
