- id: '1583530252657'
  alias: Muminskåp tänd
  description: ''
  trigger:
  - event: sunset
    offset: +00:45:00
    platform: sun
  condition:
  - condition: state
    entity_id: group.people
    state: home
  - condition: time
    weekday:
    - fri
    - sat
    - sun
  action:
  - device_id: f021ae88c9c94bb9b00a399eaab1019d
    domain: switch
    entity_id: switch.innr_sp_120_59328903_on_off
    type: turn_on
- id: '1583530546061'
  alias: Muminskåp släck
  description: ''
  trigger:
  - at: '23:00:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - fri
    - sat
    - sun
  action:
  - device_id: f021ae88c9c94bb9b00a399eaab1019d
    domain: switch
    entity_id: switch.innr_sp_120_59328903_on_off
    type: turn_off
- id: 1583772997902_boll_on
  alias: Blå boll tänd
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - device_id: 8269351cd5fd4ab7aa20a373c72279d3
    domain: switch
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_5ddf51fe_on_off
    type: turn_on
- id: 1583773386688_boll_off_vardag
  alias: Blå boll släck (vardag)
  description: ''
  trigger:
  - at: '22:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - device_id: 8269351cd5fd4ab7aa20a373c72279d3
    domain: switch
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_5ddf51fe_on_off
    type: turn_off
- id: 1583773386689_boll_off_helg
  alias: Blå boll släck (helg)
  description: ''
  trigger:
  - at: '23:59:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - device_id: 8269351cd5fd4ab7aa20a373c72279d3
    domain: switch
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_5ddf51fe_on_off
    type: turn_off
- id: '1583773805811'
  alias: TV-skåp tänd
  description: ''
  trigger:
  - at: '18:00'
    platform: time
  condition:
  - after: sunset
    condition: sun
  action:
  - device_id: 67515fccbe29472c8032217b84fb9b1b
    domain: switch
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_3d4ac3fe_on_off
    type: turn_on
- id: '1583773866555'
  alias: TV-skåp släck
  description: ''
  trigger:
  - at: '22:00:00'
    platform: time
  condition: []
  action:
  - device_id: 67515fccbe29472c8032217b84fb9b1b
    domain: switch
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_3d4ac3fe_on_off
    type: turn_off
