- id: '1583530252657'
  alias: Tänd muminskåp på helgen
  description: ''
  trigger:
  - event: sunset
    offset: +00:45:00
    platform: sun
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: all
      state: home
    - condition: time
      weekday:
      - fri
      - sat
      - sun
  action:
  - device_id: f021ae88c9c94bb9b00a399eaab1019d
    domain: switch
    entity_id: switch.innr_sp_120_59328903_on_off
    type: turn_on
- id: '1583530546061'
  alias: Släck muminskåp på helgen
  description: ''
  trigger:
  - at: '23:00:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - fri
    - sat
    - sun
  action:
  - device_id: f021ae88c9c94bb9b00a399eaab1019d
    domain: switch
    entity_id: switch.innr_sp_120_59328903_on_off
    type: turn_off
