
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate
    base_url: http://192.168.1.13:8123

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

device_tracker:
  - platform: bluetooth_tracker
    interval_seconds: 60
    consider_home: 180
    new_device_defaults:
      track_new_devices: false
  - platform: ping
    hosts:
      sony_xperia_one: 192.168.2.192

google_assistant:
  project_id: home-assistant-c84b7
  expose_by_default: true
  service_account: !include ha-state-report-account.json
  report_state: true
  exposed_domains:
    - switch
    - light

media_player:
  - platform: kodi
    name: Eris (kodi)
    host: flora.lan.glyph.se
    port: 80

# Enable workday
binary_sensor:
  - platform: workday
    country: SE

light:
  - platform: group
    name: Korgar
    entities:
      - light.philips_lta001_5a422d08_level_light_color_on_off
      - light.philips_lta001_40e83008_level_light_color_on_off
      - light.philips_lta001_bc2fab08_level_light_color_on_off