# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.11

# Text to speech
tts:
  - platform: google_translate
    base_url: http://192.168.1.13:8123

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include light_groups.yaml

device_tracker:
  - platform: bluetooth_tracker
    #    interval_seconds: 60
    consider_home: 00:10:00
    new_device_defaults:
      track_new_devices: false
#  - platform: ping
#    hosts:
#      sony_xperia_one: 192.168.2.192

google_assistant: !include google_assistant.yaml
binary_sensor: !include binary_sensors.yaml

# Move recorder to memory
recorder:
  purge_keep_days: 2
  db_url: "sqlite:///:memory:"
# Extra logs for Google Assistant debugging
#logger:
#  default: error
#  logs:
#    homeassistant.components.google_assistant: debug

input_boolean:
  nattlage:
    name: Nattläge
    icon: mdi:sleep
