# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.11

# Text to speech
tts:
  - platform: google_translate
    base_url: http://192.168.1.13:8123

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include light_groups.yaml

device_tracker:
  - platform: bluetooth_tracker
    #    interval_seconds: 60
    consider_home: 00:10:00
    new_device_defaults:
      track_new_devices: false
#  - platform: ping
#    hosts:
#      sony_xperia_one: 192.168.2.192

google_assistant:
  project_id: home-assistant-2-dca83
  expose_by_default: true
  service_account: !include google-assistant-service-account-2.json
  report_state: true
  exposed_domains:
    - switch
    - light
  entity_config:
    sensor.hallsensor_temperature:
      expose: true
    binary_sensor.skafferisensor_on_off:
      expose: true
    input_boolean.nattlage:
      expose: true

# Enable workday
binary_sensor:
  - platform: workday
    country: SE

# Move recorder to memory
recorder:
  purge_keep_days: 2
  db_url: "sqlite:///:memory:"
# Extra logs for Google Assistant debugging
#logger:
#  default: error
#  logs:
#    homeassistant.components.google_assistant: debug

input_boolean:
  nattlage:
    name: Nattläge
    icon: mdi:sleep
