- platform: group
  name: Korgar
  entities:
    - light.philips_lta001_5a422d08_level_light_color_on_off
    - light.philips_lta001_40e83008_level_light_color_on_off
    - light.philips_lta001_bc2fab08_level_light_color_on_off

- platform: switch
  name: Bl책 boll
  entity_id: switch.ikea_of_sweden_tradfri_control_outlet_5ddf51fe_on_off
- platform: switch
  name: Muminsk책p
  entity_id: switch.innr_sp_120_59328903_on_off
- platform: switch
  name: S채nglampa
  entity_id: switch.innr_sp_120_ed448903_on_off
- platform: switch
  name: TV-sk책p
  entity_id: switch.ikea_of_sweden_tradfri_control_outlet_3d4ac3fe_on_off