#- platform: group
#  name: Korgar
#  entities:
#    - light.philips_lta001_5a422d08_level_light_color_on_off
#    - light.philips_lta001_40e83008_level_light_color_on_off
#    - light.philips_lta001_bc2fab08_level_light_color_on_off

- platform: switch
  name: Kökslampor
  entity_id: switch.kokslampor
- platform: switch
  name: Kökshörn
  entity_id: switch.kokshorn

- platform: switch
  name: Badrumslampa nere
  entity_id: switch.badrumslampa_nere
- platform: switch
  name: Badrumspegel nere
  entity_id: switch.badrumspegel_nere

- platform: switch
  name: Badrumslampa uppe
  entity_id: switch.badrumslampa_uppe
- platform: switch
  name: Badrumspegel uppe
  entity_id: switch.badrumspegel_uppe

- platform: group
  name: Taklampor
  entities:
    - light.taklampa_ett
    - light.taklampa_tva
    - light.taklampa_tre
    - light.taklampa_fyra
