#- platform: group
#  name: Korgar
#  entities:
#    - light.philips_lta001_5a422d08_level_light_color_on_off
#    - light.philips_lta001_40e83008_level_light_color_on_off
#    - light.philips_lta001_bc2fab08_level_light_color_on_off

- platform: switch
  name: Blå boll
  entity_id: switch.ikea_of_sweden_tradfri_control_outlet_5ddf51fe_on_off
- platform: switch
  name: Svarta ljusstakar
  entity_id: switch.ikea_of_sweden_tradfri_control_outlet_3d4ac3fe_on_off

- platform: switch
  name: Kökslampor
  entity_id: switch.kokslampor
- platform: switch
  name: Kökshörn
  entity_id: switch.kokshorn

- platform: group
  name: Taklampor
  entities:
    - light.taklampa_ett
    - light.taklampa_tva
    - light.taklampa_tre
    - light.taklampa_fyra
