binary_sensor:
  # Tracks 2 humidity readings over 10 minutes. If the change is greater than 20%, evals to true. (20/(60*10))
  - platform: trend
    sensors:
      badrum_uppe_shower_on:
        max_samples: 2
        entity_id: sensor.fuktsensor_badrum_uppe_humidity
        sample_duration: 600
        min_gradient: 0.03333
  # Tracks 2 humidity readings over 10 minutes. If the change decrease is greater than 5%, evals to true. (-5/(60*10))
  # Bumped samples down from 4 to 2, because it was staying on way too long.
  - platform: trend
    sensors:
      badrum_uppe_shower_off:
        max_samples: 2
        entity_id: sensor.fuktsensor_badrum_uppe_humidity
        sample_duration: 600
        min_gradient: -0.00833
